---
parent: Api_v1_bank-account
name: ApiV1BankAccountPutBodyParamCustomize
description: null
authors:
- apisec Bot
type: SUITE
init: []
path: /api/v1/bank-account
endpoint: /api/v1/bank-account
method: PUT
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: "{\r\n  \"accountBalance\" : \"{{@RandomInteger}}\",\r\n  \"accountNumber\"\
    \ : \"{{@RandomInteger}}\",\r\n  \"createdBy\" : \"\",\r\n  \"createdDate\" :\
    \ \"\",\r\n  \"id\" : \"\",\r\n  \"inactive\" : false,\r\n  \"modifiedBy\" : \"\
    \",\r\n  \"modifiedDate\" : \"\",\r\n  \"user\" : {\r\n    \"createdBy\" : \"\"\
    ,\r\n    \"createdDate\" : \"\",\r\n    \"id\" : \"\",\r\n    \"inactive\" : false,\r\
    \n    \"modifiedBy\" : \"\",\r\n    \"modifiedDate\" : \"\",\r\n    \"name\" :\
    \ \"{{@Injection}}\",\r\n    \"version\" : \"\"\r\n  },\r\n  \"version\" : \"\"\
    \r\n}"
  inactive: false
useCategoryAssertion: false
assertions:
- none
cleanup: []
severity: Medium
category: customize
tags:
- V1
- test
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: '@FXLabs/Common/customize'
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
autoGenerated: true
